// Generated by CoffeeScript 1.3.3
(function() {

  window.validate = function(form) {
    var email, emailPattern;
    email = form.elements['email'].value;
    emailPattern = /^([\w.-]+)@([\w.-]+)\.([a-zA-Z.]{2,6})$/i;
    if (email.match(emailPattern)) {
      return true;
    } else {
      $('label[for="email"]').addClass('error').append('<small class="invalid">Dit email adres is niet geldig</small>');
      return false;
    }
  };

}).call(this);
