// Generated by CoffeeScript 1.3.3
(function() {

  window.validateEmail = function(email) {
    var emailPattern, noErrorMessage;
    emailPattern = /^([\w.-]+)@([\w.-]+)\.([a-zA-Z.]{2,6})$/i;
    if ($('label[for="email"] small.invalid').length === 0) {
      noErrorMessage = true;
    }
    if (email.match(emailPattern)) {
      return true;
    } else if (noErrorMessage) {
      $('label[for="email"]').append('<small class="invalid" style="display: none">Dit email adres is niet geldig</small>');
      $('small.invalid').slideDown('slow', function() {
        return $('label[for="email"]').css('animation', 'shake 1s');
      });
    }
    return false;
  };

  window.processNewsletterForm = function(form) {
    var email;
    email = form.elements['email'].value;
    if (typeof Storage !== "undefined" && Storage !== null) {
      localStorage.email = email;
    }
    return validateEmail(email);
  };

  $(function() {
    if (localStorage.email != null) {
      $("input#email").val(localStorage.email);
    }
    return $('[href^="#"]').click(function() {
      var destination, elementClicked;
      elementClicked = $(this).attr("href");
      destination = $(elementClicked).offset().top;
      $("html:not(:animated),body:not(:animated)").animate({
        scrollTop: destination - 20
      }, 500);
      return false;
    });
  });

}).call(this);
