// Generated by CoffeeScript 1.3.3
(function() {
  var isValidEmail, showEmailError;

  $(function() {
    if (localStorage.email != null) {
      $("input#email").val(localStorage.email);
    }
    return $('[href^="#"]').click(function() {
      var destination, elementClicked;
      elementClicked = $(this).attr("href");
      destination = $(elementClicked).offset().top;
      $("html:not(:animated),body:not(:animated)").animate({
        scrollTop: destination - 20
      }, 500);
      return false;
    });
  });

  isValidEmail = function(email) {
    var emailPattern;
    emailPattern = /^([\w.-]+)@([\w.-]+)\.([a-zA-Z.]{2,6})$/i;
    if (email.match(emailPattern)) {
      return true;
    } else {
      return false;
    }
  };

  showEmailError = function(message) {
    $('label[for="email"]').append('<small class="invalid" style="display: none">' + message + '</small>');
    return $('small.invalid').slideDown('slow', function() {
      return $('label[for="email"]').css('animation', 'shake 1s');
    });
  };

  window.processNewsletterForm = function(form) {
    var email, noErrorMessage;
    email = form.elements['email'].value;
    if (isValidEmail(email)) {
      if (typeof Storage !== "undefined" && Storage !== null) {
        localStorage.email = email;
      }
      return true;
    } else {
      if ($('label[for="email"] small.invalid').length === 0) {
        noErrorMessage = true;
      }
      if (noErrorMessage) {
        showEmailError("Dit email adres is niet geldig");
      }
      return false;
    }
  };

}).call(this);
